local SpellType = {
    Line = 1,
    Circular = 2,
    Cone = 3
}
local spellData = {
    {
        charName = "Aatrox",
        dangerlevel = 3,
        name = "AatroxQ",
        projectileSpeed = 450,
        radius = 285,
        range = 650,
        spellDelay = 250,
        spellKey = _Q,
        spellName = "AatroxQ",
        spellType = SpellType.Circular,
    },
    {
        charName = "Aatrox",
        dangerlevel = 1,
        name = "Blade of Torment",
        projectileSpeed = 1200,
        radius = 100,
        range = 1075,
        spellDelay = 250,
        spellKey = _E,
        spellName = "AatroxE",
        spellType = SpellType.Line,
    },
    {
        charName = "Ahri",
        dangerlevel = 2,
        missileName = "AhriOrbMissile",
        name = "Orb of Deception",
        projectileSpeed = 1750,
        radius = 100,
        range = 925,
        spellDelay = 250,
        spellKey = _Q,
        spellName = "AhriOrbofDeception",
        spellType = SpellType.Line,
    },
    {
        charName = "Ahri",
        dangerlevel = 3,
        missileName = "AhriSeduceMissile",
        name = "Charm",
        projectileSpeed = 1550,
        radius = 60,
        range = 1000,
        spellDelay = 250,
        spellKey = _E,
        spellName = "AhriSeduce",
        spellType = SpellType.Line,
        collision = 0,
    },
    {
        charName = "Ahri",
        dangerlevel = 3,
        name = "Orb of Deception Back",
        projectileSpeed = 915,
        radius = 100,
        range = 925,
        spellDelay = 250,
        spellKey = _Q,
        spellName = "AhriOrbofDeception2",
        spellType = SpellType.Line,
    },
    {
        charName = "Alistar",
        dangerlevel = 3,
        name = "Pulverize",
        radius = 365,
        range = 365,
        spellKey = _Q,
        spellName = "Pulverize",
        spellType = SpellType.Circular,
    },
    {
        charName = "Amumu",
        dangerlevel = 4,
        name = "CurseoftheSadMummy",
        radius = 560,
        range = 560,
        spellDelay = 250,
        spellKey = _R,
        spellName = "CurseoftheSadMummy",
        spellType = SpellType.Circular,
    },
    {
        charName = "Amumu",
        dangerlevel = 3,
        missileName = "SadMummyBandageToss",
        name = "Bandage Toss",
        projectileSpeed = 2000,
        radius = 80,
        range = 1100,
        spellDelay = 250,
        spellKey = _Q,
        spellName = "BandageToss",
        spellType = SpellType.Line,
        collision = 0,
    },
    {
        charName = "Anivia",
        dangerlevel = 3,
        missileName = "FlashFrostSpell",
        name = "Flash Frost",
        projectileSpeed = 850,
        radius = 110,
        range = 1250,
        spellDelay = 250,
        spellKey = _Q,
        spellName = "FlashFrostSpell",
        spellType = SpellType.Line,
    },
    {
        angle = 25,
        charName = "Annie",
        dangerlevel = 2,
        name = "Incinerate",
        radius = 80,
        range = 625,
        spellDelay = 250,
        spellKey = _W,
        spellName = "Incinerate",
        spellType = SpellType.Cone,
    },
    {
        charName = "Annie",
        dangerlevel = 4,
        name = "InfernalGuardian",
        radius = 290,
        range = 600,
        spellDelay = 250,
        spellKey = _R,
        spellName = "InfernalGuardian",
        spellType = SpellType.Circular,
    },
    {
        charName = "Ashe",
        dangerlevel = 3,
        name = "Enchanted Arrow",
        projectileSpeed = 1600,
        radius = 130,
        range = 25000,
        spellDelay = 250,
        spellKey = _R,
        spellName = "EnchantedCrystalArrow",
        spellType = SpellType.Line,
        --collisionH = 0,
    },
    {
        angle = 5,
        charName = "Ashe",
        dangerlevel = 2,
        --missileName = "VolleyAttack",
        name = "Volley",
        projectileSpeed = 1500,
        radius = 20,
        range = 1200,
        spellDelay = 250,
        spellKey = _W,
        spellName = "Volley",
        spellType = SpellType.Line,
        isSpecial = true,
        collision = 0,
    },
    {
        charName = "Azir",
        dangerlevel = 2,
        name = "AzirQ",
        projectileSpeed = 1000,
        radius = 80,
        range = 800,
        spellDelay = 250,
        spellKey = _Q,
        spellName = "AzirQ",
        spellType = SpellType.Line,
        usePackets = true,
        isSpecial = true,
    },
    {
        charName = "Bard",
        dangerlevel = 2,
        name = "BardQ",
        missileName = "BardQMissile",
        projectileSpeed = 1600,
        radius = 60,
        range = 950,
        spellDelay = 250,
        spellKey = _Q,
        spellName = "BardQ",
        spellType = SpellType.Line,
        collision = 0,
    },
    {
        charName = "Blitzcrank",
        dangerlevel = 3,
        extraDelay = 75,
        missileName = "RocketGrabMissile",
        name = "Rocket Grab",
        projectileSpeed = 1800,
        radius = 70,
        range = 1050,
        spellDelay = 250,
        spellKey = _Q,
        spellName = "RocketGrab",
        spellType = SpellType.Line,
        collision = 0,
    },
    {
        charName = "Brand",
        dangerlevel = 3,
        missileName = "BrandBlazeMissile",
        name = "BrandBlaze",
        projectileSpeed = 2000, --1600
        radius = 60,
        range = 1100,
        spellDelay = 250,
        spellKey = _Q,
        spellName = "BrandBlaze",
        spellType = SpellType.Line,
        collision = 0,
        
    },
    {
        charName = "Brand",
        dangerlevel = 2,
        name = "Pillar of Flame",
        radius = 250,
        range = 1100,
        spellDelay = 850,
        spellKey = _W,
        spellName = "BrandFissure",
        spellType = SpellType.Circular,
    },
    {
        charName = "Braum",
        dangerlevel = 4,
        name = "GlacialFissure",
        projectileSpeed = 1125,
        radius = 100,
        range = 1250,
        spellDelay = 500,
        spellKey = _R,
        spellName = "BraumRWrapper",
        spellType = SpellType.Line,
    },
    {
        charName = "Braum",
        dangerlevel = 3,
        missileName = "BraumQMissile",
        name = "BraumQ",
        projectileSpeed = 1200,
        --spellDelay = 30000,
        spellDelay = 250,   
        radius = 100,
        range = 1000,             
        spellKey = _Q,
        spellName = "BraumQ",
        spellType = SpellType.Line,
        collision = 0,
    },
    {
        charName = "Caitlyn",
        dangerlevel = 2,
        name = "Piltover Peacemaker",
        projectileSpeed = 2200,
        radius = 90,
        range = 1300,
        spellDelay = 625,
        spellKey = _Q,
        spellName = "CaitlynPiltoverPeacemaker",
        spellType = SpellType.Line,
    },
    {
        charName = "Caitlyn",
        dangerlevel = 2,
        missileName = "CaitlynEntrapmentMissile",
        name = "Caitlyn Entrapment",
        projectileSpeed = 2000,
        radius = 80,
        range = 950,
        spellDelay = 125,
        spellKey = _E,
        spellName = "CaitlynEntrapment",
        spellType = SpellType.Line,
        collision = 0,
    },
    {
        angle = 40,
        charName = "Cassiopeia",
        dangerlevel = 4,
        name = "CassiopeiaPetrifyingGaze",
        radius = 20,
        range = 825,
        spellDelay = 500,
        spellKey = _R,
        spellName = "CassiopeiaPetrifyingGaze",
        spellType = SpellType.Cone,
    },
    {
        charName = "Cassiopeia",
        dangerlevel = 1,
        name = "CassiopeiaNoxiousBlast",
        radius = 200,
        range = 600,
        spellDelay = 825,
        spellKey = _Q,
        spellName = "CassiopeiaNoxiousBlast",
        spellType = SpellType.Circular,
    },
    {
        charName = "Cassiopeia",
        dangerlevel = 1,
        name = "CassiopeiaMiasma",
        radius = 220,
        range = 850,
        spellDelay = 250,
        projectileSpeed = 2500,
        spellKey = _W,
        spellName = "CassiopeiaMiasma",
        spellType = SpellType.Circular,
    },
    {
        angle = 30,
        charName = "Chogath",
        dangerlevel = 2,
        name = "FeralScream",
        radius = 20,
        range = 650,
        spellDelay = 250,
        spellKey = _W,
        spellName = "FeralScream",
        spellType = SpellType.Cone,
    },
    {
        charName = "Chogath",
        dangerlevel = 3,
        name = "Rupture",
        radius = 250,
        range = 950,
        spellDelay = 1200,
        spellKey = _Q,
        spellName = "Rupture",
        spellType = SpellType.Circular,
        extraDrawHeight = 45,
    },
    {
        charName = "Corki",
        dangerlevel = 1,
        missileName = "MissileBarrageMissile2",
        name = "Missile Barrage big",
        projectileSpeed = 2000,
        radius = 40,
        range = 1500,
        spellDelay = 175,
        spellKey = _R,
        spellName = "MissileBarrage2",
        spellType = SpellType.Line,
        collision = 0,
        
    },
    {
        charName = "Corki",
        dangerlevel = 2,
        missileName = "PhosphorusBombMissile",
        name = "Phosphorus Bomb",
        projectileSpeed = 1125,
        radius = 270,
        range = 825,
        spellDelay = 500,
        spellKey = _Q,
        spellName = "PhosphorusBomb",
        spellType = SpellType.Circular,
        extraDrawHeight = 110,
    },
    {
        charName = "Corki",
        dangerlevel = 1,
        missileName = "MissileBarrageMissile",
        name = "Missile Barrage",
        projectileSpeed = 2000,
        radius = 40,
        range = 1300,
        spellDelay = 175,
        spellKey = _R,
        spellName = "MissileBarrage",
        spellType = SpellType.Line,
        collision = 0,
    },
    {
        angle = 25,
        charName = "Darius",
        dangerlevel = 3,
        name = "DariusAxeGrabCone",
        radius = 20,
        range = 570,
        spellDelay = 320,
        spellKey = _E,
        spellName = "DariusAxeGrabCone",
        spellType = SpellType.Cone,
    },
    {
        charName = "Diana",
        dangerlevel = 3,
        name = "DianaArc",
        projectileSpeed = 1400,
        radius = 50,
        range = 850,
        fixedRange = true,
        spellDelay = 250,
        spellKey = _Q,
        spellName = "DianaArc",
        spellType = SpellType.Arc,
        hasEndExplosion = true,
        secondaryRadius = 195,
        extraEndTime = 250,
    },
    {
        charName = "DrMundo",
        dangerlevel = 1,
        missileName = "InfectedCleaverMissile",
        name = "Infected Cleaver",
        projectileSpeed = 2000,
        radius = 60,
        range = 1050,
        spellDelay = 250,
        spellKey = _Q,
        spellName = "InfectedCleaverMissileCast",
        spellType = SpellType.Line,
        collision = 0,
    },
    {
        charName = "Draven",
        dangerlevel = 3,
        missileName = "DravenR",
        name = "DravenR",
        projectileSpeed = 2000,
        radius = 160,
        range = 25000,
        spellDelay = 500,
        spellKey = _R,
        spellName = "DravenRCast",
        spellType = SpellType.Line,
    },
    {
        charName = "Draven",
        dangerlevel = 2,
        missileName = "DravenDoubleShotMissile",
        name = "Stand Aside",
        projectileSpeed = 1400,
        radius = 130,
        range = 1100,
        spellDelay = 250,
        spellKey = _E,
        spellName = "DravenDoubleShot",
        spellType = SpellType.Line,
    },
    {
        charName = "Ekko",
        dangerlevel = 3,
        name = "EkkoQ",
        missileName = "ekkoqmis",
        projectileSpeed = 1650,
        radius = 60,
        range = 950,
        spellDelay = 250,
        spellKey = _Q,
        spellName = "EkkoQ",
        spellType = SpellType.Line,
        collisionH = 0,
    },
    {
        charName = "Ekko",
        dangerlevel = 3,
        name = "EkkoW",
        radius = 375,
        range = 1600,
        spellDelay = 3750,
        spellKey = _W,
        spellName = "EkkoW",
        spellType = SpellType.Circular,
    },
    {
        charName = "Ekko",
        dangerlevel = 3,
        name = "EkkoR",
        radius = 375,
        range = 1600,
        spellDelay = 250,
        spellKey = _R,
        spellName = "EkkoR",
        spellType = SpellType.Circular,
        isSpecial = true,
    },
    {
        charName = "Elise",
        dangerlevel = 3,
        name = "Cocoon",
        projectileSpeed = 1600,
        radius = 70,
        range = 1100,
        spellDelay = 250,
        spellKey = _E,
        spellName = "EliseHumanE",
        spellType = SpellType.Line,
        collision = 0,
    },
    {
        charName = "Evelynn",
        dangerlevel = 3,
        name = "EvelynnR",
        radius = 350,
        range = 650,
        spellDelay = 250,
        spellKey = _R,
        spellName = "EvelynnR",
        spellType = SpellType.Circular,
    },
    {
        charName = "Ezreal",
        dangerlevel = 2,
        missileName = "EzrealMysticShotMissile",
        name = "Mystic Shot",
        projectileSpeed = 2000,
        radius = 60,
        range = 1200,
        spellDelay = 250,
        spellKey = _Q,
        spellName = "EzrealMysticShot",
        extraSpellNames = { "ezrealmysticshotwrapper", },
        spellType = SpellType.Line,
        collision = 0,
    },
    {
        charName = "Ezreal",
        dangerlevel = 2,
        name = "Trueshot Barrage",
        projectileSpeed = 2000,
        radius = 160,
        range = 20000,
        spellDelay = 1000,
        spellKey = _R,
        spellName = "EzrealTrueshotBarrage",
        spellType = SpellType.Line,
    },
    {
        charName = "Ezreal",
        dangerlevel = 1,
        missileName = "EzrealEssenceFluxMissile",
        name = "Essence Flux",
        projectileSpeed = 1600,
        radius = 80,
        range = 1050,
        spellDelay = 250,
        spellKey = _W,
        spellName = "EzrealEssenceFlux",
        spellType = SpellType.Line,
    },
    {
        charName = "Ezreal",
        dangerlevel = 1,
        name = "Essence Flux2",
        radius = 250,
        range = 1050,
        spellDelay = 825,
        spellKey = _W,
        spellName = "EzrealEssenceFlux",
        spellType = SpellType.Circular,
    },
    {
        charName = "Fiora",
        dangerlevel = 1,
        missileName = "FioraWMissile",
        name = "FioraW",
        projectileSpeed = 3200,
        radius = 70,
        range = 750,
        spellDelay = 500,
        spellKey = _W,
        spellName = "FioraW",
        spellType = SpellType.Line,
    },
    {
        charName = "Fizz",
        dangerlevel = 2,
        name = "FizzPiercingStrike",
        projectileSpeed = 1400,
        radius = 150,
        range = 550,
        spellDelay = 0,
        spellKey = _Q,
        spellName = "FizzPiercingStrike",
        spellType = SpellType.Line,
        isSpecial = true,
    },
    {
        charName = "Fizz",
        dangerlevel = 3,
        missileName = "FizzMarinerDoomMissile",
        name = "Fizz ULT",
        projectileSpeed = 1350,
        radius = 120,
        range = 1275,
        spellDelay = 250,
        spellKey = _R,
        spellName = "FizzMarinerDoom",
        spellType = SpellType.Line,
        collisionH = 0,
        --hasEndExplosion = true,
        secondaryRadius = 250,
        useEndPosition = true,
        --extraEndTime = 1000,
    },
    {
        charName = "Galio",
        dangerlevel = 2,
        name = "GalioRighteousGust",
        projectileSpeed = 1300,
        radius = 160,
        range = 1280,
        spellKey = _E,
        spellName = "GalioRighteousGust",
        spellType = SpellType.Line,
    },
    {
        charName = "Galio",
        dangerlevel = 2,
        name = "GalioResoluteSmite",
        projectileSpeed = 1200,
        radius = 235,
        range = 1040,
        spellDelay = 250,
        spellKey = _Q,
        spellName = "GalioResoluteSmite",
        spellType = SpellType.Circular,
    },
    {
        charName = "Galio",
        dangerlevel = 4,
        name = "GalioIdolOfDurand",
        radius = 600,
        range = 600,
        spellKey = _R,
        spellName = "GalioIdolOfDurand",
        spellType = SpellType.Circular,
    },
    {
        charName = "Gnar",
        dangerlevel = 2,
        name = "Boulder Toss",
        projectileSpeed = 2000,
        radius = 90,
        range = 1150,
        spellDelay = 500,
        spellKey = _Q,
        spellName = "gnarbigq",
        spellType = SpellType.Line,
        collision = 0,
    },
    {
        charName = "Gnar",
        dangerlevel = 3,
        name = "GnarUlt",
        radius = 500,
        range = 500,
        spellDelay = 250,
        spellKey = _R,
        spellName = "GnarR",
        spellType = SpellType.Circular,
    },
    {
        charName = "Gnar",
        dangerlevel = 3,
        name = "Wallop",
        projectileSpeed = math.huge,
        radius = 100,
        range = 600,
        spellDelay = 600,
        spellKey = _W,
        spellName = "gnarbigw",
        spellType = SpellType.Line,
    },
    {
        charName = "Gnar",
        dangerlevel = 2,
        name = "Boomerang Throw",
        projectileSpeed = 2400,
        radius = 60,
        range = 1185,
        spellDelay = 250,
        spellKey = _Q,
        spellName = "GnarQ",
        spellType = SpellType.Line,
        collision = 0,
    },
    {
        charName = "Gnar",
        dangerlevel = 2,
        name = "GnarE",
        spellName = "GnarE",
        range = 475,
        spellDelay = 0,
        radius = 150,
        fixedRange = true,
        projectileSpeed = 900,
        spellKey = _E,
        spellType = SpellType.Circular,
    },
    {
        charName = "Gnar",
        dangerlevel = 2,
        name = "GnarBigE",
        spellName = "gnarbige",
        range = 475,
        spellDelay = 0,
        radius = 100,
        fixedRange = true,
        projectileSpeed = 800,
        spellKey = _E,
        spellType = SpellType.Circular,
    },
    {
        charName = "Gragas",
        dangerlevel = 2,
        name = "Barrel Roll",
        projectileSpeed = 1000,
        radius = 250,
        range = 975,
        spellDelay = 500,
        spellKey = _Q,
        spellName = "GragasQ",
        spellType = SpellType.Circular,
    },
    {
        charName = "Gragas",
        dangerlevel = 3,
        name = "Barrel Roll",
        projectileSpeed = 1200,
        radius = 200,
        range = 950,
        spellDelay = 0,
        spellKey = _E,
        spellName = "GragasE",
        spellType = SpellType.Line,
    },
    {
        charName = "Gragas",
        dangerlevel = 4,
        name = "GragasExplosiveCask",
        projectileSpeed = 1750,
        radius = 350,
        range = 1050,
        spellDelay = 250,
        spellKey = _R,
        spellName = "GragasR",
        spellType = SpellType.Circular,
    },
    {
        charName = "Graves",
        dangerlevel = 2,
        missileName = "GravesQLineMis",
        extraMissileNames = { "GravesQReturn" },
        name = "Buckshot",
        projectileSpeed = 3000,
        radius = 40,
        range = 825,
        spellDelay = 250,
        spellKey = _Q,
        spellName = "GravesQLineSpell",
        spellType = SpellType.Line,
    },
    {
        charName = "Graves",
        dangerlevel = 3,
        missileName = "GravesChargeShotShot",
        name = "Collateral Damage",
        projectileSpeed = 2100,
        radius = 100,
        range = 1000,
        spellDelay = 250,
        spellKey = _R,
        spellName = "GravesChargeShot",
        spellType = SpellType.Line,
    },
    {
        charName = "Hecarim",
        dangerlevel = 3,
        name = "HecarimUlt",
        projectileSpeed = 1100,
        radius = 300,
        range = 1500,
        spellDelay = 10,
        spellKey = _R,
        spellName = "HecarimUlt",
        spellType = SpellType.Circular,
    },
    {
        charName = "Heimerdinger",
        dangerlevel = 2,
        missileName = "HeimerdingerESpell",
        name = "HeimerdingerE",
        projectileSpeed = 1750,
        radius = 135,
        range = 925,
        spellDelay = 325,
        spellKey = _E,
        spellName = "HeimerdingerE",
        spellType = SpellType.Circular,
    },
    {
        charName = "Heimerdinger",
        dangerlevel = 2,
        name = "HeimerdingerW",
        projectileSpeed = 2500,
        radius = 50,
        range = 1350,
        spellDelay = 250,
        spellKey = _W,
        spellName = "HeimerdingerW",
        spellType = SpellType.Line,
        isSpecial = true,
        defaultOff = true,
    },
    {
        charName = "Heimerdinger",
        dangerlevel = 2,
        name = "Turret Energy Blast",
        projectileSpeed = 1650,
        radius = 50,
        range = 1000,
        spellDelay = 435,
        spellKey = _Q,
        spellName = "HeimerdingerTurretEnergyBlast",
        spellType = SpellType.Line,
        isSpecial = true,
    },
    {
        charName = "Heimerdinger",
        dangerlevel = 3,
        name = "Turret Energy Blast",
        projectileSpeed = 1650,
        radius = 75,
        range = 1000,
        spellDelay = 350,
        spellKey = _Q,
        spellName = "HeimerdingerTurretBigEnergyBlast",
        spellType = SpellType.Line,
    },
    {
        charName = "Illaoi",
        dangerlevel = 3,
        name = "IllaoiQ",
        radius = 100,
        range = 850,
        spellDelay = 750,
        spellKey = _Q,
        spellName = "IllaoiQ",
        spellType = SpellType.Line,
    },
    {
        charName = "Illaoi",
        dangerlevel = 3,
        missileName = "Illaoiemis",
        name = "IllaoiE",
        projectileSpeed = 1900,
        radius = 50,
        range = 950,
        spellDelay = 250,
        spellKey = _E,
        spellName = "IllaoiE",
        spellType = SpellType.Line,
    },
    {
        charName = "Illaoi",
        dangerlevel = 3,
        name = "IllaoiR",
        range = 0,
        radius = 450,
        spellDelay = 500,
        spellKey = _R,
        spellName = "IllaoiR",
        spellType = SpellType.Circular,
    },
    {
        charName = "Irelia",
        dangerlevel = 2,
        missileName = "ireliatranscendentbladesspell",
        name = "IreliaTranscendentBlades",
        projectileSpeed = 1600,
        radius = 120,
        range = 1200,
        spellKey = _R,
        spellDelay = 0,
        spellName = "IreliaTranscendentBlades",
        spellType = SpellType.Line,
        usePackets = true,
        defaultOff = true,
    },
    {
        charName = "Janna",
        dangerlevel = 2,
        missileName = "HowlingGaleSpell",
        name = "HowlingGaleSpell",
        projectileSpeed = 900,
        radius = 120,
        range = 1700,
        spellKey = _Q,
        spellName = "HowlingGale",
        spellType = SpellType.Line,
        usePackets = true,
    },
    {
        charName = "JarvanIV",
        dangerlevel = 2,
        name = "JarvanIVDragonStrike",
        projectileSpeed = 2000,
        radius = 80,
        range = 845,
        spellDelay = 250,
        spellKey = _Q,
        spellName = "JarvanIVDragonStrike",
        spellType = SpellType.Line,
    },
    {
        charName = "JarvanIV",
        dangerlevel = 2,
        name = "JarvanIVDragonStrike",
        projectileSpeed = 1800,
        radius = 120,
        range = 845,
        spellDelay = 250,
        spellKey = _Q,
        spellName = "JarvanIVDragonStrike2",
        spellType = SpellType.Line,
        useEndPosition = true,
    },
    {
        charName = "JarvanIV",
        dangerlevel = 3,
        name = "JarvanIVCataclysm",
        projectileSpeed = 1900,
        radius = 350,
        range = 825,
        spellDelay = 0,
        spellKey = _R,
        spellName = "JarvanIVCataclysm",
        spellType = SpellType.Circular,
    },
    {
        charName = "Jayce",
        dangerlevel = 3,
        missileName = "JayceShockBlastMis",
        name = "JayceShockBlastCharged",
        projectileSpeed = 2350,
        radius = 70,
        range = 1570,
        spellDelay = 250,
        spellKey = _Q,
        spellName = "jayceshockblast",
        spellType = SpellType.Line,
        collision = 0,
        hasEndExplosion = true,
        secondaryRadius = 250,
    },
    {
        charName = "Jayce",
        dangerlevel = 2,
        missileName = "JayceShockBlastMis",
        name = "JayceShockBlast",
        projectileSpeed = 1450,
        radius = 70,
        range = 1050,
        spellDelay = 250,
        spellKey = _Q,
        spellName = "jayceshockblast",
        spellType = SpellType.Line,
        collision = 0,
        hasEndExplosion = true,
        secondaryRadius = 175,
    },
    {
        charName = "Jinx",
        dangerlevel = 3,
        name = "JinxR",
        projectileSpeed = 1700, --accelerates to 2600
        radius = 140,
        range = 25000,
        spellDelay = 600,
        spellKey = _R,
        spellName = "JinxR",
        spellType = SpellType.Line,
        --collisionH = 0,
    },
    {
        charName = "Jinx",
        dangerlevel = 3,
        --missileName = "JinxWMissile",
        name = "Zap",
        projectileSpeed = 3300,
        radius = 60,
        range = 1500,
        spellDelay = 600,
        spellKey = _W,
        spellName = "JinxWMissile",
        spellType = SpellType.Line,
        collision = 0,
    },
    {
        charName = "Kalista",
        dangerlevel = 2,
        missileName = "kalistamysticshotmistrue",
        name = "KalistaQ",
        projectileSpeed = 2000,
        radius = 70,
        range = 1200,
        spellDelay = 350,
        spellKey = _Q,
        spellName = "KalistaMysticShot",
        spellType = SpellType.Line,
        collision = 0,
    },
    {
        charName = "Karma",
        dangerlevel = 2,
        missileName = "KarmaQMissile",
        name = "KarmaQ",
        projectileSpeed = 1700,
        radius = 90,
        range = 1050,
        spellDelay = 250,
        spellKey = _Q,
        spellName = "KarmaQ",
        spellType = SpellType.Line,
        collision = 0,
    },
    {
        charName = "Karma",
        dangerlevel = 2,
        missileName = "KarmaQMissileMantra",
        name = "KarmaQMantra",
        projectileSpeed = 1700,
        radius = 90,
        range = 1050,
        spellDelay = 250,
        spellKey = _Q,
        spellName = "KarmaQMissileMantra",
        spellType = SpellType.Line,
        usePackets = true,
        collision = 0,
    },
    {
        charName = "Karthus",
        dangerlevel = 1,
        name = "Lay Waste",
        radius = 190,
        range = 875,
        spellDelay = 900,
        spellKey = _Q,
        spellName = "KarthusLayWasteA1",
        spellType = SpellType.Circular,
        extraSpellNames = { "karthuslaywastea2", "karthuslaywastea3", "karthuslaywastedeada1", "karthuslaywastedeada2", "karthuslaywastedeada3" },
    },
    {
        charName = "Kassadin",
        dangerlevel = 1,
        name = "RiftWalk",
        radius = 270,
        range = 700,
        spellDelay = 250,
        spellKey = _R,
        spellName = "RiftWalk",
        spellType = SpellType.Circular,
    },
    {
        angle = 40,
        charName = "Kassadin",
        dangerlevel = 2,
        name = "ForcePulse",
        radius = 20,
        range = 700,
        spellDelay = 250,
        spellKey = _E,
        spellName = "ForcePulse",
        spellType = SpellType.Cone,
    },
    {
        charName = "Kennen",
        dangerlevel = 2,
        missileName = "KennenShurikenHurlMissile1",
        name = "Thundering Shuriken",
        projectileSpeed = 1700,
        radius = 50,
        range = 1175,
        spellDelay = 180,
        spellKey = _Q,
        spellName = "KennenShurikenHurlMissile1",
        spellType = SpellType.Line,
        collision = 0,
    },
    {
        charName = "Khazix",
        dangerlevel = 1,
        missileName = "KhazixWMissile",
        name = "KhazixW",
        projectileSpeed = 1700,
        radius = 70,
        range = 1100,
        spellDelay = 250,
        spellKey = _W,
        spellName = "KhazixW",
        spellType = SpellType.Line,
        collision = 0,
    },
    {
        angle = 22,
        charName = "Khazix",
        dangerlevel = 1,
        isThreeWay = true,
        name = "khazixwlong",
        projectileSpeed = 1700,
        radius = 70,
        range = 1025,
        spellDelay = 250,
        spellKey = _W,
        spellName = "khazixwlong",
        spellType = SpellType.Line,
        collision = 0,
    },
    {
        charName = "KogMaw",
        dangerlevel = 1,
        name = "Caustic Spittle",
        projectileSpeed = 1650,
        radius = 70,
        range = 1125,
        spellDelay = 250,
        spellKey = _Q,
        spellName = "KogMawQ",
        spellType = SpellType.Line,
        collision = 0,
    },
    {
        charName = "KogMaw",
        dangerlevel = 1,
        name = "KogMawVoidOoze",
        projectileSpeed = 1400,
        radius = 120,
        range = 1360,
        spellDelay = 250,
        spellKey = _E,
        spellName = "KogMawVoidOoze",
        spellType = SpellType.Line,
    },
    {
        charName = "KogMaw",
        dangerlevel = 2,
        name = "Living Artillery",
        radius = 235,
        range = 2200,
        spellDelay = 1100,
        spellKey = _R,
        spellName = "KogMawLivingArtillery",
        spellType = SpellType.Circular,
    },
    {
        charName = "Leblanc",
        dangerlevel = 2,
        name = "Ethereal Chains R",
        projectileSpeed = 1600,
        radius = 70,
        range = 960,
        spellDelay = 250,
        spellKey = _R,
        spellName = "LeblancSoulShackleM",
        spellType = SpellType.Line,
        collision = 0,
    },
    {
        charName = "Leblanc",
        dangerlevel = 2,
        name = "Ethereal Chains",
        projectileSpeed = 1600,
        radius = 70,
        range = 960,
        spellDelay = 250,
        spellKey = _E,
        spellName = "LeblancSoulShackle",
        spellType = SpellType.Line,
        collision = 0,
    },
    {
        charName = "Leblanc",
        dangerlevel = 1,
        name = "LeblancSlideM",
        projectileSpeed = 1600,
        radius = 250,
        range = 725,
        spellDelay = 250,
        spellKey = _R,
        spellName = "LeblancSlideM",
        spellType = SpellType.Circular,
    },
    {
        charName = "Leblanc",
        dangerlevel = 1,
        name = "LeblancSlide",
        projectileSpeed = 1600,
        radius = 250,
        range = 725,
        spellDelay = 250,
        spellKey = _W,
        spellName = "LeblancSlide",
        spellType = SpellType.Circular,
    },
    {
        charName = "LeeSin",
        dangerlevel = 3,
        name = "Sonic Wave",
        projectileSpeed = 1800,
        radius = 60,
        range = 1100,
        spellDelay = 250,
        spellKey = _Q,
        spellName = "BlindMonkQOne",
        spellType = SpellType.Line,
        collision = 0,
    },
    {
        charName = "Leona",
        dangerlevel = 4,
        name = "Leona Solar Flare",
        radius = 300,
        range = 1200,
        spellDelay = 1000,
        spellKey = _R,
        spellName = "LeonaSolarFlare",
        spellType = SpellType.Circular,
    },
    {
        charName = "Leona",
        dangerlevel = 3,
        extraDistance = 65,
        missileName = "LeonaZenithBladeMissile",
        name = "Zenith Blade",
        projectileSpeed = 2000,
        radius = 70,
        range = 975,
        spellDelay = 200,
        spellKey = _E,
        spellName = "LeonaZenithBlade",
        spellType = SpellType.Line,
    },
    {
        charName = "Lissandra",
        dangerlevel = 3,
        name = "LissandraW",
        projectileSpeed = math.huge,
        radius = 450,
        range = 725,
        spellDelay = 250,
        spellKey = _W,
        spellName = "LissandraW",
        spellType = SpellType.Circular,
    },
    {
        charName = "Lissandra",
        dangerlevel = 2,
        name = "Ice Shard",
        projectileSpeed = 2250,
        radius = 75,
        range = 825,
        spellDelay = 250,
        spellKey = _Q,
        spellName = "LissandraQ",
        spellType = SpellType.Line,
    },
    {
        charName = "Lucian",
        dangerlevel = 1,
        defaultOff = true,
        name = "LucianW",
        projectileSpeed = 1600,
        radius = 80,
        range = 1000,
        spellDelay = 300,
        spellKey = _W,
        spellName = "LucianW",
        spellType = SpellType.Line,
        collision = 0,
    },
    {
        charName = "Lucian",
        dangerlevel = 2,
        --defaultOff = true,
        isSpecial = true,
        name = "LucianQ",
        projectileSpeed = math.huge,
        radius = 65,
        range = 1140,
        spellDelay = 350,
        spellKey = _Q,
        spellName = "LucianQ",
        spellType = SpellType.Line,
    },
    {
        charName = "Lulu",
        dangerlevel = 2,
        missileName = "LuluQMissile",
        name = "LuluQ",
        projectileSpeed = 1450,
        radius = 80,
        range = 925,
        spellDelay = 250,
        spellKey = _Q,
        spellName = "LuluQ",
        spellType = SpellType.Line,
        isSpecial = true,
    },
    {
        charName = "Lux",
        dangerlevel = 2,
        name = "LuxLightStrikeKugel",
        projectileSpeed = 1400,
        radius = 340,
        range = 1100,
        extraEndTime = 1000,
        spellDelay = 250,
        spellKey = _E,
        spellName = "LuxLightStrikeKugel",
        spellType = SpellType.Circular,
    },
    {
        charName = "Lux",
        dangerlevel = 3,
        name = "Lux Malice Cannon",
        projectileSpeed = math.huge,
        radius = 110,
        range = 3500,
        spellDelay = 1000,
        spellKey = _R,
        spellName = "LuxMaliceCannon",
        spellType = SpellType.Line,
    },
    {
        charName = "Lux",
        dangerlevel = 3,
        missileName = "LuxLightBindingMis",
        name = "Light Binding",
        projectileSpeed = 1200,                
        radius = 70,
        range = 1300,
        spellDelay = 250,
        spellKey = _Q,
        spellName = "LuxLightBinding",
        spellType = SpellType.Line,
        collision = 0,
    },
    {
        charName = "Malphite",
        dangerlevel = 4,
        name = "UFSlash",
        projectileSpeed = 2000,
        radius = 300,
        range = 1000,
        spellDelay = 0,
        spellKey = _R,
        spellName = "UFSlash",
        spellType = SpellType.Circular,
    },
    {
        charName = "Malzahar",
        dangerlevel = 2,
        --extraEndTime = 750,
        --defaultOff = true,
        isSpecial = true,
        isWall = true,
        --missileName = "AlZaharCalloftheVoidMissile",
        name = "AlZaharCalloftheVoid",
        projectileSpeed = 1600,
        radius = 85,
        range = 900,
        sideRadius = 400,
        spellDelay = 1000,
        spellKey = _Q,
        spellName = "AlZaharCalloftheVoid",
        spellType = SpellType.Line,
    },
    {
        charName = "MonkeyKing",
        dangerlevel = 3,
        name = "MonkeyKingSpinToWin",
        radius = 225,
        range = 300,
        spellDelay = 250,
        spellKey = _R,
        spellName = "MonkeyKingSpinToWin",
        spellType = SpellType.Circular,
        defaultOff = true,
    },
    {
        charName = "Morgana",
        dangerlevel = 3,
        name = "Dark Binding",
        projectileSpeed = 1200,
        radius = 80,
        range = 1300,
        spellDelay = 250,
        spellKey = _Q,
        spellName = "DarkBindingMissile",
        spellType = SpellType.Line,
        collision = 0,
    },
    {
        charName = "Nami",
        dangerlevel = 3,
        name = "NamiQ",
        radius = 200,
        range = 875,
        spellDelay = 1000,
        spellKey = _Q,
        spellName = "NamiQ",
        spellType = SpellType.Circular,
    },
    {
        charName = "Nami",
        dangerlevel = 4,
        missileName = "NamiRMissile",
        name = "NamiR",
        projectileSpeed = 850,
        radius = 250,
        range = 2750,
        spellDelay = 500,
        spellKey = _R,
        spellName = "NamiR",
        spellType = SpellType.Line,
    },
    {
        charName = "Nautilus",
        dangerlevel = 3,
        missileName = "NautilusAnchorDragMissile",
        name = "Dredge Line",
        projectileSpeed = 2000,
        radius = 90,
        range = 1250,
        spellDelay = 250,
        spellKey = _Q,
        spellName = "NautilusAnchorDrag",
        spellType = SpellType.Line,
        collision = 0,
    },
    {
        charName = "Nidalee",
        dangerlevel = 2,
        name = "Javelin Toss",
        projectileSpeed = 1300,
        radius = 60,
        range = 1500,
        spellDelay = 250,
        spellKey = _Q,
        spellName = "JavelinToss",
        spellType = SpellType.Line,
        collision = 0,
    },
    {
        charName = "Nocturne",
        dangerlevel = 1,
        name = "NocturneDuskbringer",
        projectileSpeed = 1400,
        radius = 60,
        range = 1125,
        spellDelay = 250,
        spellKey = _Q,
        spellName = "NocturneDuskbringer",
        spellType = SpellType.Line,
    },
    {
        charName = "Olaf",
        dangerlevel = 1,
        name = "Undertow",
        projectileSpeed = 1600,
        radius = 90,
        range = 1000,
        spellDelay = 250,
        spellKey = _Q,
        spellName = "OlafAxeThrowCast",
        spellType = SpellType.Line,
    },
    {
        charName = "Orianna",
        dangerlevel = 2,
        --hasEndExplosion = true,
        name = "OrianaIzunaCommand",
        projectileSpeed = 1200,
        radius = 80,
        secondaryRadius = 170,
        range = 2000,
        spellDelay = 0,
        spellKey = _Q,
        spellName = "OrianaIzunaCommand",
        spellType = SpellType.Line,
        isSpecial = true,
        useEndPosition = true,
    },
    {
        charName = "Orianna",
        dangerlevel = 4,
        name = "OrianaDetonateCommand",
        radius = 410,
        range = 410,
        spellDelay = 500,
        spellKey = _R,
        spellName = "OrianaDetonateCommand",
        spellType = SpellType.Circular,
    },
    {
        charName = "Orianna",
        dangerlevel = 2,
        name = "OrianaDissonanceCommand",
        radius = 250,
        range = 1825,
        spellKey = _W,
        spellName = "OrianaDissonanceCommand",
        spellType = SpellType.Circular,
    },
    {
        angle = 35,
        charName = "Pantheon",
        dangerlevel = 2,
        name = "Heartseeker",
        radius = 100,
        range = 650,
        spellDelay = 1000,
        spellKey = _E,
        spellName = "PantheonE",
        spellType = SpellType.Cone,
    },
    {
        charName = "Poppy",
        dangerlevel = 2,
        name = "Hammer Shock",
        radius = 100,
        range = 450,
        spellDelay = 500,
        spellKey = _Q,
        spellName = "PoppyQ",
        spellType = SpellType.Line,
    },
    {
        charName = "Poppy",
        dangerlevel = 3,
        name = "Keeper's Verdict",
        radius = 110,
        range = 450,
        spellDelay = 300,
        spellKey = _R,
        spellName = "PoppyRSpellInstant",
        spellType = SpellType.Line,
    },
    {
        charName = "Poppy",
        dangerlevel = 3,
        name = "Keeper's Verdict",
        radius = 100,
        range = 1150,
        projectileSpeed = 1750,
        spellDelay = 300,
        spellKey = _R,
        spellName = "PoppyRSpell",
        missileName = "PoppyRMissile",
        spellType = SpellType.Line,
    },
    {
        charName = "Quinn",
        dangerlevel = 2,
        missileName = "QuinnQMissile",
        name = "QuinnQ",
        projectileSpeed = 1550,
        radius = 80,
        range = 1050,
        spellDelay = 250,
        spellKey = _Q,
        spellName = "QuinnQ",
        spellType = SpellType.Line,
        collision = 0,
    },
    {
        charName = "RekSai",
        dangerlevel = 2,
        missileName = "RekSaiQBurrowedMis",
        name = "RekSaiQ",
        projectileSpeed = 1950,
        radius = 65,
        range = 1500,
        spellDelay = 125,
        spellKey = _Q,
        spellName = "reksaiqburrowed",
        spellType = SpellType.Line,
        collision = 0,
    },
    {
        charName = "Rengar",
        dangerlevel = 2,
        missileName = "RengarEFinal",
        name = "Bola Strike",
        projectileSpeed = 1500,
        radius = 70,
        range = 1000,
        spellDelay = 250,
        spellKey = _E,
        spellName = "RengarE",
        spellType = SpellType.Line,
        extraMissileNames = { "RengarEFinalMAX"},
        collision = 0,
    },
    {
        angle = 15,
        charName = "Riven",
        dangerlevel = 2,
        isThreeWay = true,
        name = "WindSlash",
        projectileSpeed = 1600,
        radius = 100,
        range = 1100,
        spellDelay = 250,
        spellKey = _R,
        spellName = "rivenizunablade",
        spellType = SpellType.Line,
        isSpecial = true,
    },
    {
        charName = "Riven",
        dangerlevel = 2,
        defaultOff = true,
        name = "RivenW",
        projectileSpeed = 1500,
        radius = 280,
        range = 650,
        spellDelay = 267,
        spellKey = _W,
        spellName = "RivenMartyr",
        spellType = SpellType.Circular,
    },
    {
        charName = "Rumble",
        dangerlevel = 1,
        missileName = "RumbleGrenadeMissile",
        name = "RumbleGrenade",
        projectileSpeed = 2000,
        radius = 90,
        range = 950,
        spellDelay = 250,
        spellKey = _E,
        spellName = "RumbleGrenade",
        spellType = SpellType.Line,
        collision = 0,
    },
    {
        charName = "Ryze",
        dangerlevel = 2,
        missileName = "RyzeQ",
        name = "RyzeQ",
        projectileSpeed = 1700,
        radius = 60,
        range = 900,
        spellDelay = 250,
        spellKey = _Q,
        spellName = "RyzeQ",
        spellType = SpellType.Line,
        collision = 0,
    },
    {
        charName = "Sejuani",
        dangerlevel = 3,
        name = "Arctic Assault",
        projectileSpeed = 1600,
        radius = 70,
        range = 900,
        spellDelay = 0,
        spellKey = _Q,
        spellName = "SejuaniArcticAssault",
        spellType = SpellType.Line,
    },
    {
        charName = "Sejuani",
        dangerlevel = 4,
        missileName = "SejuaniGlacialPrison",
        name = "SejuaniR",
        projectileSpeed = 1600,
        radius = 110,
        range = 1200,
        spellDelay = 250,
        spellKey = _R,
        spellName = "SejuaniGlacialPrisonCast",
        spellType = SpellType.Line,
    },
    {
        charName = "Shen",
        dangerlevel = 3,
        name = "ShadowDash",
        projectileSpeed = 1250,
        radius = 75,
        range = 700,
        spellDelay = 0,
        spellKey = _E,
        spellName = "ShenShadowDash",
        spellType = SpellType.Line,
    },
    {
        charName = "Shyvana",
        dangerlevel = 1,
        name = "ShyvanaFireball",
        projectileSpeed = 1700,
        radius = 60,
        range = 950,
        spellKey = _E,
        spellName = "ShyvanaFireball",
        spellType = SpellType.Line,
    },
    {
        charName = "Shyvana",
        dangerlevel = 3,
        name = "ShyvanaTransformCast",
        projectileSpeed = 1100,
        radius = 160,
        range = 1000,
        spellDelay = 10,
        spellKey = _R,
        spellName = "ShyvanaTransformCast",
        spellType = SpellType.Line,
    },
    {
        charName = "Sion",
        dangerlevel = 2,
        --missileName = "SionEMissile",
        name = "SionE",
        projectileSpeed = 1800,
        radius = 80,
        range = 800,
        spellDelay = 250,
        spellKey = _E,
        spellName = "SionE",
        spellType = SpellType.Line,
        isSpecial = true,
    },
    {
        charName = "Sivir",
        dangerlevel = 2,
        missileName = "SivirQMissile",
        name = "Boomerang Blade",
        projectileSpeed = 1350,
        radius = 100,
        range = 1275,
        spellDelay = 250,
        spellKey = _Q,
        spellName = "SivirQ",
        spellType = SpellType.Line,
    },
    {
        charName = "Skarner",
        dangerlevel = 2,
        missileName = "SkarnerFractureMissile",
        name = "SkarnerFracture",
        projectileSpeed = 1400,
        radius = 60,
        range = 1000,
        spellDelay = 250,
        spellKey = _E,
        spellName = "SkarnerFracture",
        spellType = SpellType.Line,
    },
    {
        charName = "Sona",
        dangerlevel = 4,
        name = "Crescendo",
        projectileSpeed = 2400,
        radius = 150,
        range = 1000,
        spellDelay = 250,
        spellKey = _R,
        spellName = "SonaR",
        spellType = SpellType.Line,
    },
    {
        charName = "Soraka",
        dangerlevel = 2,
        name = "SorakaQ",
        projectileSpeed = 1100,
        radius = 260,
        range = 970,
        spellDelay = 250,
        spellKey = _Q,
        spellName = "SorakaQ",
        spellType = SpellType.Circular,
    },
    {
        charName = "Soraka",
        dangerlevel = 3,
        name = "SorakaE",
        radius = 275,
        range = 925,
        spellDelay = 1750,
        spellKey = _E,
        spellName = "SorakaE",
        spellType = SpellType.Circular,
    },
    {
        charName = "Swain",
        dangerlevel = 3,
        name = "Nevermove",
        radius = 250,
        range = 900,
        spellDelay = 1100,
        spellKey = _W,
        spellName = "SwainShadowGrasp",
        spellType = SpellType.Circular,
    },
    {
        angle = 30,
        charName = "Syndra",
        dangerlevel = 3,
        name = "SyndraE",
        usePackets = true,
        projectileSpeed = 1500,
        radius = 140,
        range = 800,
        spellDelay = 250,
        spellKey = _E,
        spellName = "SyndraE",
        spellType = SpellType.Line,
    },
    {
        charName = "Syndra",
        dangerlevel = 2,
        name = "SyndraW",
        projectileSpeed = 1450,
        radius = 220,
        range = 925,
        spellDelay = 0,
        spellKey = _W,
        spellName = "syndrawcast",
        spellType = SpellType.Circular,
    },
    {
        charName = "Syndra",
        dangerlevel = 2,
        name = "SyndraQ",
        radius = 210,
        range = 800,
        spellDelay = 600,
        spellKey = _Q,
        spellName = "SyndraQ",
        spellType = SpellType.Circular,
    },
    {
        charName = "TahmKench",
        dangerlevel = 2,
        missileName = "tahmkenchqmissile",
        name = "TahmKenchQ",
        projectileSpeed = 2000,
        spellDelay = 250,
        radius = 90,
        range = 951,
        spellKey = _Q,
        spellName = "TahmKenchQ",
        spellType = SpellType.Line,
        collision = 0,
    },
    {
        angle = 20,
        charName = "Talon",
        dangerlevel = 2,
        isThreeWay = true,
        name = "TalonRake",
        projectileSpeed = 2300,
        radius = 75,
        range = 780,
        spellKey = _W,
        spellName = "TalonRake",
        spellType = SpellType.Line,
        splits = 3,
        isSpecial = true,
    },
    {
        charName = "Thresh",
        dangerlevel = 3,
        missileName = "ThreshQMissile",
        name = "ThreshQ",
        projectileSpeed = 1900,
        radius = 70,
        range = 1100,
        spellDelay = 500,
        spellKey = _Q,
        spellName = "ThreshQ",
        spellType = SpellType.Line,
        collision = 0,
    },
    {
        charName = "Thresh",
        dangerlevel = 3,
        missileName = "ThreshEMissile1",
        name = "ThreshE",
        projectileSpeed = 2000,
        radius = 110,
        range = 1075,
        spellDelay = 0,
        defaultOff = true,
        spellKey = _E,
        spellName = "ThreshE",
        spellType = SpellType.Line,
        usePackets = true,
    },
    {
        angle = 28,
        charName = "TwistedFate",
        dangerlevel = 2,
        isThreeWay = true,
        missileName = "SealFateMissile",
        name = "Loaded Dice",
        projectileSpeed = 1000,
        radius = 40,
        range = 1450,
        spellDelay = 250,
        spellKey = _Q,
        spellName = "WildCards",
        spellType = SpellType.Line,
        isSpecial = true,
    },
    {
        charName = "Twitch",
        dangerlevel = 2,
        name = "Loaded Dice",
        projectileSpeed = 4000,
        radius = 60,
        range = 1100,
        spellDelay = 250,
        spellKey = _R,
        spellName = "TwitchSprayandPrayAttack",
        spellType = SpellType.Line,
        defaultOff = true,
    },
    {
        charName = "Urgot",
        dangerlevel = 1,
        name = "Acid Hunter",
        projectileSpeed = 1600,
        radius = 60,
        range = 1000,
        spellDelay = 175,
        spellKey = _Q,
        spellName = "UrgotHeatseekingLineMissile",
        spellType = SpellType.Line,
        collision = 0,
    },
    {
        charName = "Urgot",
        dangerlevel = 2,
        name = "Plasma Grenade",
        projectileSpeed = 1750,
        radius = 250,
        range = 900,
        spellDelay = 250,
        spellKey = _E,
        spellName = "UrgotPlasmaGrenade",
        spellType = SpellType.Circular,
    },
    {
        charName = "Varus",
        dangerlevel = 1,
        defaultOff = true,
        name = "Varus E",
        projectileSpeed = 1500,
        radius = 235,
        range = 925,
        spellDelay = 250,
        spellKey = _E,
        spellName = "VarusE",
        spellType = SpellType.Circular,
    },
    {
        charName = "Varus",
        dangerlevel = 2,
        missileName = "VarusQMissile",
        name = "VarusQMissile",
        projectileSpeed = 1900,
        radius = 70,
        range = 1600,
        spellDelay = 0,
        spellKey = _Q,
        spellName = "varusq",
        spellType = SpellType.Line,
        usePackets = true,
    },
    {
        charName = "Varus",
        dangerlevel = 3,
        name = "VarusR",
        projectileSpeed = 1950,
        radius = 100,
        range = 1200,
        spellDelay = 250,
        spellKey = _R,
        spellName = "VarusR",
        spellType = SpellType.Line,
        collisionH = 0,
    },
    {
        charName = "Veigar",
        dangerlevel = 2,
        name = "VeigarBalefulStrike",
        radius = 70,
        range = 950,
        spellDelay = 250,
        projectileSpeed = 1750,
        spellKey = _Q,
        spellName = "VeigarBalefulStrike",
        missileName = "VeigarBalefulStrikeMis",
        spellType = SpellType.Line,
    },
    {
        charName = "Veigar",
        dangerlevel = 2,
        name = "VeigarDarkMatter",
        radius = 225,
        range = 900,
        spellDelay = 1350,
        spellKey = _W,
        spellName = "VeigarDarkMatter",
        spellType = SpellType.Circular,
        
    },
    {
        charName = "Veigar",
        dangerlevel = 3,
        name = "VeigarEventHorizon",
        radius = 425,
        range = 700,
        spellDelay = 500,
        extraEndTime = 3500,
        spellKey = _E,
        spellName = "VeigarEventHorizon",
        spellType = SpellType.Circular,
        defaultOff = true,
    },
    {
        charName = "Velkoz",
        dangerlevel = 2,
        name = "VelkozE",
        projectileSpeed = 1500,
        radius = 225,
        range = 950,
        spellKey = _E,
        spellName = "VelkozE",
        spellType = SpellType.Circular,
    },
    {
        charName = "Velkoz",
        dangerlevel = 1,
        name = "VelkozW",
        projectileSpeed = 1700,
        radius = 88,
        range = 1100,
        spellKey = _W,
        spellName = "VelkozW",
        spellType = SpellType.Line,
    },
    {
        charName = "Velkoz",
        dangerlevel = 2,
        name = "VelkozQMissileSplit",
        projectileSpeed = 2100,
        radius = 45,
        range = 1100,
        spellKey = _Q,
        spellName = "VelkozQMissileSplit",
        spellType = SpellType.Line,
        usePackets = true,
        collision = 0,
    },
    {
        charName = "Velkoz",
        dangerlevel = 2,
        name = "VelkozQ",
        projectileSpeed = 1300,
        radius = 50,
        range = 1250,
        spellKey = _Q,
        missileName = "VelkozQMissile",
        spellName = "VelkozQ",
        spellType = SpellType.Line,
        collision = 0,
    },
    {
        charName = "Vi",
        dangerlevel = 3,
        name = "ViQMissile",
        projectileSpeed = 1500,
        radius = 90,
        range = 725,
        spellKey = _Q,
        spellName = "ViQMissile",
        spellType = SpellType.Line,
        usePackets = true,
        defaultOff = true,
        collisionH = 0,
    },
    {
        charName = "Viktor",
        dangerlevel = 2,
        missileName = "ViktorDeathRayMissile",
        name = "ViktorDeathRay",
        projectileSpeed = 780,
        radius = 80,
        range = 800,
        spellKey = _E,
        spellName = "ViktorDeathRay",
        extraMissileNames = { "viktoreaugmissile", },
        spellType = SpellType.Line,
        usePackets = true,
    },
    {
        charName = "Viktor",
        dangerlevel = 2,
        name = "ViktorDeathRay3",
        projectileSpeed = math.huge,
        spellDelay = 500,
        radius = 80,
        range = 800,
        spellKey = _E,
        spellName = "ViktorDeathRay3",
        spellType = SpellType.Line,                
    },
    {
        charName = "Viktor",
        dangerlevel = 2,
        missileName = "ViktorDeathRayMissile2",
        name = "ViktorDeathRay2",
        projectileSpeed = 1500,
        radius = 80,
        range = 800,
        spellKey = _E,
        spellName = "ViktorDeathRay2",
        spellType = SpellType.Line,
        usePackets = true,
    },
    {
        charName = "Viktor",
        dangerlevel = 2,
        name = "GravitonField",
        radius = 300,
        range = 625,
        spellDelay = 1500,
        spellKey = _W,
        spellName = "ViktorGravitonField",
        spellType = SpellType.Circular,
        defaultOff = true,
    },
    {
        charName = "Vladimir",
        dangerlevel = 3,
        name = "VladimirHemoplague",
        radius = 375,
        range = 700,
        spellDelay = 389,
        spellKey = _R,
        spellName = "VladimirHemoplague",
        spellType = SpellType.Circular,
    },
    {
        charName = "Xerath",
        dangerlevel = 2,
        name = "XerathArcaneBarrage2",
        radius = 280,
        range = 1100,
        spellDelay = 750,
        spellKey = _W,
        spellName = "XerathArcaneBarrage2",
        spellType = SpellType.Circular,
        extraDrawHeight = 45,
    },
    {
        charName = "Xerath",
        dangerlevel = 1,
        name = "XerathArcanopulse2",
        projectileSpeed = math.huge,
        radius = 70,
        range = 1525,
        spellDelay = 500,
        spellKey = _Q,
        spellName = "xeratharcanopulse2",
        useEndPosition = true,
        spellType = SpellType.Line,
    },
    {
        charName = "Xerath",
        dangerlevel = 2,
        name = "XerathLocusOfPower2",
        radius = 200,
        range = 5600,
        spellDelay = 600,
        spellKey = _R,
        spellName = "xerathrmissilewrapper",
        spellType = SpellType.Circular,
    },
    {
        charName = "Xerath",
        dangerlevel = 3,
        missileName = "XerathMageSpearMissile",
        name = "XerathMageSpear",
        projectileSpeed = 1600,
        spellDelay = 200,
        radius = 60,
        range = 1125,
        spellKey = _E,
        spellName = "XerathMageSpear",
        spellType = SpellType.Line,
        collision = 0,
    },
    {
        charName = "Yasuo",
        dangerlevel = 3,
        missileName = "yasuoq3mis",
        name = "Steel Tempest3",
        projectileSpeed = 1200,
        radius = 90,
        range = 1100,
        spellDelay = 250,
        spellKey = _Q,
        spellName = "yasuoq3w",
        spellType = SpellType.Line,
    },
    {
        charName = "Yasuo",
        dangerlevel = 2,
        name = "Steel Tempest",
        projectileSpeed = math.huge,
        radius = 35,
        range = 500,
        spellDelay = 250,
        spellKey = _Q,
        spellName = "YasuoQW",
        extraSpellNames = {"yasuoq2w"},
        spellType = SpellType.Line,
        defaultOff = true,
    },
    {
        charName = "Zed",
        dangerlevel = 2,
        name = "ZedShuriken",                
        projectileSpeed = 1700,
        radius = 50,
        range = 925,
        spellDelay = 250,
        spellKey = _Q,
        spellName = "ZedQ",
        spellType = SpellType.Line,
    },
    {
        charName = "Zed",
        dangerlevel = 1,
        name = "ZedE",
        radius = 290,
        range = 290,
        spellKey = _E,
        spellName = "ZedE",
        spellType = SpellType.Circular,
        isSpecial = true,
        defaultOff = true,
    },
    {
        charName = "Ziggs",
        dangerlevel = 1,
        name = "ZiggsE",
        projectileSpeed = 3000,
        radius = 235,
        range = 2000,
        spellDelay = 250,
        spellKey = _E,
        spellName = "ZiggsE",
        spellType = SpellType.Circular,
    },
    {
        charName = "Ziggs",
        dangerlevel = 1,
        name = "ZiggsW",
        projectileSpeed = 3000,
        radius = 275,
        range = 2000,
        spellDelay = 250,
        spellKey = _W,
        spellName = "ZiggsW",
        spellType = SpellType.Circular,
    },
    {
        charName = "Ziggs",
        dangerlevel = 2,
        name = "ZiggsQ",
        projectileSpeed = 1700,
        radius = 150,
        range = 850,                
        spellDelay = 250,
        spellKey = _Q,
        spellName = "ZiggsQ",
        spellType = SpellType.Circular,
        isSpecial = true,
        noProcess = true,
    },
    {
        charName = "Ziggs",
        dangerlevel = 4,
        name = "ZiggsR",
        projectileSpeed = 1500,
        radius = 550,
        range = 5300,
        spellDelay = 1500,
        spellKey = _R,
        spellName = "ZiggsR",
        spellType = SpellType.Circular,
    },
    {
        charName = "Zilean",
        dangerlevel = 2,
        name = "ZileanQ",
        projectileSpeed = 2000,
        radius = 250,
        range = 900,
        spellDelay = 300,
        spellKey = _Q,
        spellName = "ZileanQ",
        spellType = SpellType.Circular,
    },
    {
        charName = "Zyra",
        dangerlevel = 3,
        name = "Grasping Roots",
        projectileSpeed = 1400, --1150
        radius = 70,
        range = 1150,
        spellDelay = 250,
        spellKey = _E,
        spellName = "ZyraGraspingRoots",
        spellType = SpellType.Line,
    },
    {
        charName = "Zyra",
        dangerlevel = 2,
        missileName = "zyrapassivedeathmanager",
        name = "Zyra Passive",
        projectileSpeed = 1900,
        radius = 70,
        range = 1474,
        spellDelay = 500,
        spellKey = _Q,
        spellName = "zyrapassivedeathmanager",
        spellType = SpellType.Line,
    },
    {
        charName = "Zyra",
        dangerlevel = 2,
        name = "Deadly Bloom",
        radius = 260,
        range = 825,
        spellDelay = 800,
        spellKey = _Q,
        spellName = "ZyraQFissure",
        spellType = SpellType.Circular,
    },
    {
        charName = "Zyra",
        dangerlevel = 4,
        name = "ZyraR",
        radius = 525,
        range = 700,
        spellDelay = 500,
        spellKey = _R,
        spellName = "ZyraBrambleZone",
        spellType = SpellType.Circular,
    }
}
require("Inspired")
AutoUpdate("/Inspired-gos/scripts/master/Aimbot.version", "/Inspired-gos/scripts/master/Aimbot.version", "Aimbot.lua", 1)
require("OpenPredict")
local lastSpell -- { endPos, targetID, startPos, spellID }
local allowCast = {}
-- helper classes S
class "Spell"
function Spell:__init(slot, type, name, range, width, delay, speed, collision, aoe)
	self.slot, self.type, self.name, self.range, self.width, self.delay, self.speed, self.collision, self.aoe = slot, type, name, range, width, delay, speed, collision, aoe
end

function Spell:Cast(target, hitchance, sourcePos)
	if target and GetDistance(target, sourcePos) > (self.range <= 0 and self.width or self.range) then return end
	if self.aoe then
		local pred = ({GetLinearAOEPrediction, GetCircularAOEPrediction, GetConicAOEPrediction})[self.type]
		local p = pred(target, self, sourcePos)
		if p.hitChance >= (hitchance or 0.25) then
            allowCast[self.slot] = true
			myHero:CastSpell(self.slot, p.castPos.x, p.castPos.z)
		end
	else
        local p = GetPrediction(target, self, sourcePos)
        if p.hitChance >= (hitchance or 0.25) and (not self.collision or not p:mCollision(self.collision)) then
            allowCast[self.slot] = true
            myHero:CastSpell(self.slot, p.castPos.x, p.castPos.z)
        end
	end
end

function Spell:Draw(around, color)
	local pos = around or myHero.pos
	DrawCircle3D(pos.x, pos.y, pos.z, self.range <= 0 and self.width or self.range, 1, color or 0xffffffff, 32)
end
-- helper classes E
local mySpells = {}
for i, v in pairs(spellData) do
    if v.charName == myHero.charName then
        mySpells[v.spellKey] = Spell(v.spellKey, v.spellType, v.name, v.range, v.radius*2, v.spellDelay*0.001, v.projectileSpeed or math.huge, v.collision)
    end
end
local function SortEnemies(pos, mode)
    local enemyHeroes = table.copy(GetEnemyHeroes()) 
    local sort = {
        [1] = function(pos) table.sort(enemyHeroes, function(a,b) return GetDistance(pos,a)<GetDistance(pos,b) end) end,
        [2] = function() table.sort(enemyHeroes, function(a,b) return a.physReduction*a.magicReduction*a.health<b.physReduction*b.magicReduction*b.health end) end,
        [3] = function() table.sort(enemyHeroes, function(a,b) return (a.totalDamage*a.attackSpeed*a.range/1000+a.magicArmor+a.armor+a.ap*(1-a.cdr))*a.level*a.health/a.maxHealth>(b.totalDamage*b.attackSpeed*b.range/1000+b.magicArmor+b.armor+b.ap*(1-b.cdr))*b.level*b.health/b.maxHealth end) end,
        [4] = function() table.sort(enemyHeroes, function(a,b) return a.distance<b.distance end) end,
        [5] = function() table.sort(enemyHeroes, function(a,b) return a.distance>b.distance end) end,
        [6] = function()--[[**FAP**]]end,
    }
    sort[mode](pos)
    return enemyHeroes
end
local Config
Callback.Add("Load", function()
    Config = MenuConfig("Aimbot", "Aimbot")
    Config:Menu("Spells")
    local c = 0
    for i, v in pairs(mySpells) do
        if c > 0 then
            Config.Spells:Info("ii"..i, "")
        end
        c = c + 1
        Config.Spells:Info("i"..i, v.name)
        Config.Spells:Boolean("d"..i, "Draw it!", true)
        Config.Spells:Boolean("u"..i, "Use it!", true)
        Config.Spells:Slider("h"..i, "Hitchance ", 0.25, 0, 0.50, 0.05)
        Config.Spells:DropDown("m"..i, "Target Selector Mode", 1, {"Closest to CastPos", "Fastest Dead", "Highest Threat", "Closest to myHero", "Furthest to myHero", "Random"})
    end
    Config:Boolean("on", "Enabled", true)
    Config:Key("off", "Disabled", 32)
end)
Callback.Add("SpellCast", function(iSpell)
    if allowCast[iSpell.spellID] then
        allowCast[iSpell.spellID] = false
        return
    end
    if mySpells[iSpell.spellID] and Config.Spells["u"..iSpell.spellID]:Value() and EnemiesAround(myHero.pos, mySpells[iSpell.spellID].range) > 0 then 
        lastSpell = table.copy(iSpell)
        lastSpell.time = os.clock()
        BlockCast()
    end
end)
Callback.Add("Tick", function()
    if lastSpell then
        if lastSpell.time+0.125 < os.clock() then
            lastSpell = nil
            return
        end
        local iSpell = lastSpell.spellID
        if EnemiesAround(myHero.pos, mySpells[iSpell].range) == 0 then
            lastSpell = nil
            return
        end
        if myHero:CanUseSpell(iSpell) > 0 then
            lastSpell = nil
            return
        end
        local targets = SortEnemies(lastSpell.endPos, Config.Spells["m"..iSpell]:Value())
        for i=1, #targets do
            local target = targets[i]
            if target and target.valid then
                mySpells[iSpell]:Cast(target, Config.Spells["h"..iSpell]:Value())
            end
        end
    end
end)
Callback.Add("Draw", function()
    for i, v in pairs(mySpells) do
        if Config.Spells["d"..i] and Config.Spells["d"..i]:Value() then
            v:Draw(myHero.pos)
        end
    end
end)
